### ISSUE TITLE
Add a new Tetris Game using React.js

### ISSUE THREAD

**Issue by 2021eo3ar** [Yoga-Vignesh/Tetris#5]
I would like to make a tetris game using React.js

**Comment by 2021eo3ar** [comment]
@Yoga-Vignesh kindly assign me this issue with hacktoberfest label, I will make a tetris game with all the functionality and will comp up with a better solution.

**Comment by Yoga-Vignesh** [comment]
I actually want this game to be Clear for beginners, not interested in upgrading it. If I want any updates in future I'll let you know.

**Comment by 2021eo3ar** [comment]
ok
